name: insta_app_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  story_view: ^0.16.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mockPhoto.jpg
    - assets/mockPhoto1.jpg
    - assets/mockPhoto2.jpg
